global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
- job_name: spring-app
  scrape_interval: 5s
  metrics_path: '/actuator/prometheus'
  scheme: http
  static_configs:
    - targets: ["192.168.3.10:8090"]